# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

	[entity.minecraft]
		chicken = true
		axolotl = true
		bee = true
		donkey = true
		cow = true
		fox = true
		tropical_fish = true
		slime = true
		pig = true
		pillager = true
		skeleton = true
		iron_golem = true
		bat = true
		cat = true
		zombie = true
		armor_stand = true
		sheep = true
		player = true
		item = true
		villager = true
		zombie_villager = true
		item_frame = true
		horse = true
		hopper_minecart = true
		vindicator = true
		falling_block = true
		minecart = true
		evoker = true
		cave_spider = true
		glow_squid = true
		witch = true
		squid = true
		spider = true
		creeper = true
		enderman = true

	[entity.ore_creeper]
		iron_creeper = true
		gold_creeper = true
		copper_creeper = true
		redstone_creeper = true
		emerald_creeper = true
		coal_creeper = true
		lapis_lazuli_creeper = true

	[entity.nemos-creatures]
		wild_boar = true
