[General]
	#Range: 0.0 ~ 100.0
	"explosion radius" = 4.0

["Coal Creeper"]
	#Range: 0.0 ~ 100.0
	"explosion radius" = 3.75
	#Range: -64 ~ 320
	"max spawn Y level" = 320

["Copper Creeper"]
	#Range: 0.0 ~ 100.0
	"explosion radius" = 3.75
	#Range: -64 ~ 320
	"max spawn Y level" = 320

["Diamond Creeper"]
	#Range: 0.0 ~ 100.0
	"explosion radius" = 3.75
	#Range: -64 ~ 320
	"max spawn Y level" = 320

["Emerald Creeper"]
	#Range: 0.0 ~ 100.0
	"explosion radius" = 3.75
	#Range: -64 ~ 320
	"max spawn Y level" = 320

["Gold Creeper"]
	#Range: 0.0 ~ 100.0
	"explosion radius" = 3.75
	#Range: -64 ~ 320
	"max spawn Y level" = 320

["Iron Creeper"]
	#Range: 0.0 ~ 100.0
	"explosion radius" = 3.75
	#Range: -64 ~ 320
	"max spawn Y level" = 320

["Lapis Lazuli Creeper"]
	#Range: 0.0 ~ 100.0
	"explosion radius" = 3.75
	#Range: -64 ~ 320
	"max spawn Y level" = 320

["Nether Gold Creeper"]
	#Range: 0.0 ~ 100.0
	"explosion radius" = 3.75
	#Range: -64 ~ 320
	"max spawn Y level" = 320

["Nether Quartz Creeper"]
	#Range: 0.0 ~ 100.0
	"explosion radius" = 3.75
	#Range: -64 ~ 320
	"max spawn Y level" = 320

["Redstone Creeper"]
	#Range: 0.0 ~ 100.0
	"explosion radius" = 3.75
	#Range: -64 ~ 320
	"max spawn Y level" = 320

#Configure Mob spawn weight & min/max group size. Set weight to 0 to disable.
["Coal Creeper - Fabric"]
	#Range: 0 ~ 500
	Weight = 60
	#Range: 0 ~ 100
	"Min Group Size" = 1
	#Range: 0 ~ 100
	"Max Group Size" = 2

["Copper Creeper - Fabric"]
	#Range: 0 ~ 500
	Weight = 60
	#Range: 0 ~ 100
	"Min Group Size" = 1
	#Range: 0 ~ 100
	"Max Group Size" = 2

["Diamond Creeper - Fabric"]
	#Range: 0 ~ 500
	Weight = 20
	#Range: 0 ~ 100
	"Min Group Size" = 1
	#Range: 0 ~ 100
	"Max Group Size" = 2

["Emerald Creeper - Fabric"]
	#Range: 0 ~ 500
	Weight = 20
	#Range: 0 ~ 100
	"Min Group Size" = 1
	#Range: 0 ~ 100
	"Max Group Size" = 2

["Gold Creeper - Fabric"]
	#Range: 0 ~ 500
	Weight = 60
	#Range: 0 ~ 100
	"Min Group Size" = 1
	#Range: 0 ~ 100
	"Max Group Size" = 2

["Iron Creeper - Fabric"]
	#Range: 0 ~ 500
	Weight = 80
	#Range: 0 ~ 100
	"Min Group Size" = 1
	#Range: 0 ~ 100
	"Max Group Size" = 2

["Lapis Lazuli Creeper - Fabric"]
	#Range: 0 ~ 500
	Weight = 50
	#Range: 0 ~ 100
	"Min Group Size" = 1
	#Range: 0 ~ 100
	"Max Group Size" = 2

["Redstone Creeper - Fabric"]
	#Range: 0 ~ 500
	Weight = 40
	#Range: 0 ~ 100
	"Min Group Size" = 1
	#Range: 0 ~ 100
	"Max Group Size" = 2

["Nether Gold Creeper - Fabric"]
	#Range: 0 ~ 500
	Weight = 20
	#Range: 0 ~ 100
	"Min Group Size" = 1
	#Range: 0 ~ 100
	"Max Group Size" = 2

["Nether Quartz Creeper - Fabric"]
	#Range: 0 ~ 500
	Weight = 20
	#Range: 0 ~ 100
	"Min Group Size" = 1
	#Range: 0 ~ 100
	"Max Group Size" = 2
